exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('articles').del()
      .then(function () {
        // Inserts seed entries
        return knex('articles').insert([
          { articleTitle: 'Hawar Daun Jagung: Penyebab, Gejala, dan Pengendalian', articleDesc: 'Hawar daun jagung, atau Corn Leaf Blight, disebabkan oleh jamur Bipolaris maydis dan Exserohilum turcicum. Penyakit ini mengakibatkan bercak cokelat pada daun yang berkembang menjadi bercak besar dengan tepi tidak beraturan. Kondisi ini mengurangi fotosintesis dan hasil panen jagung. Penyakit ini menyebar cepat dalam kondisi cuaca lembap dan hangat. Pengendalian hawar daun melibatkan penggunaan varietas jagung tahan penyakit, rotasi tanaman untuk mengurangi inokulum jamur, dan aplikasi fungisida yang tepat. Manajemen sisa tanaman dan pemantauan lapangan secara rutin juga penting untuk mencegah penyebaran penyakit ini. Dengan langkah-langkah ini, petani dapat meminimalkan dampak hawar daun dan memastikan hasil panen yang optimal', articleImg: 'https://storage.googleapis.com/cleferdev/articles/HAWAR%20DAUN%20JAGUNG.jpg' },
          { articleTitle: 'Karat Daun Jagung: Penyebab, Gejala, dan Pengendalian', articleDesc: 'Karat daun pada jagung, disebabkan oleh jamur Puccinia sorghi, adalah penyakit umum yang dapat menurunkan hasil panen. Gejalanya berupa pustula kecil berwarna oranye hingga cokelat pada daun, yang melepaskan spora dan menyebar melalui angin. Infeksi yang parah mengakibatkan nekrosis daun, mengurangi kemampuan fotosintesis dan pertumbuhan tanaman. Penyakit ini berkembang pesat dalam kondisi lembap dan hangat. Pengendalian efektif melibatkan penanaman varietas tahan, rotasi tanaman untuk mengurangi inokulum, dan aplikasi fungisida sesuai anjuran. Praktik manajemen lahan yang baik, seperti mengelola sisa tanaman dan menjaga jarak tanam untuk sirkulasi udara yang optimal, juga penting. Pemantauan rutin dan tindakan pencegahan proaktif dapat membantu menjaga kesehatan dan produktivitas tanaman jagung.', articleImg: 'https://storage.googleapis.com/cleferdev/articles/KARAT%20DAUN%20JAGUNG.jpg' },
          { articleTitle: 'Bercak Daun Jagung: Penyebab, Gejala, dan Pengendalian', articleDesc: 'Bercak daun jagung, atau Gray Leaf Spot (GLS), disebabkan oleh jamur Cercospora zeae-maydis. Penyakit ini menimbulkan bercak-bercak kecil berwarna kuning hingga abu-abu pada daun yang berkembang menjadi bercak panjang berbentuk persegi panjang. Kondisi parah menyebabkan daun mengering dan mati, mengganggu fotosintesis dan menurunkan hasil panen. Penyakit ini menyebar dalam kondisi hangat dan lembap. Pengendalian bercak daun mencakup penanaman varietas jagung yang tahan terhadap GLS, rotasi tanaman untuk mengurangi inokulum, dan penggunaan fungisida sesuai anjuran. Manajemen sisa tanaman dan pemantauan rutin juga penting. Dengan pendekatan ini, petani dapat mengurangi dampak negatif bercak daun dan memastikan produktivitas tanaman jagung yang lebih baik.', articleImg: 'https://storage.googleapis.com/cleferdev/articles/BERCAK%20DAUN%20JAGUNG.jpg' },
          { articleTitle: 'Tips Merawat Jagung Agar Tetap Sehat', articleDesc: ' Merawat tanaman jagung agar tetap sehat dan produktif memerlukan langkah-langkah yang cermat. Pemilihan benih berkualitas dan tahan penyakit adalah langkah pertama yang krusial. Persiapan lahan yang baik, dengan tanah yang gembur dan kaya bahan organik, memastikan akar dapat tumbuh optimal. Penyiraman harus cukup, terutama pada awal pertumbuhan dan saat pembentukan tongkol, dengan menjaga tanah tetap lembab namun tidak berlebihan. Pemupukan berimbang menggunakan nitrogen, fosfor, dan kalium sesuai kebutuhan sangat penting untuk pertumbuhan yang optimal. Pengendalian hama dan penyakit melalui pemantauan rutin dan penggunaan pestisida secara bijaksana, serta penyiangan gulma secara teratur, membantu menghindari persaingan sumber daya dan infeksi penyakit. Praktik rotasi tanaman dan pengelolaan sisa tanaman setelah panen juga penting untuk mengurangi risiko penumpukan hama dan penyakit di lahan. Jarak tanam yang tepat memastikan sirkulasi udara yang baik dan mengurangi kelembapan berlebih yang dapat memicu penyakit. Pemantauan rutin dan penanganan cepat terhadap masalah yang muncul seperti gejala penyakit atau serangan hama sangat penting untuk mencegah penyebaran lebih lanjut. Dengan langkah-langkah ini, petani dapat merawat tanaman jagung dengan baik, memastikan pertumbuhan yang sehat, dan menghasilkan panen yang maksimal.', articleImg: 'https://storage.googleapis.com/cleferdev/articles/JAGUNG%20SEHAT.jpg' }
        ]);
      });
  };
  